### ISSUE TITLE
SCANsat-pre has not been updated since v9

### ISSUE THREAD

**Issue by RJPercival** [KSP-CKAN/CKAN-meta-dev#8]
The latest dev version is v15.

**Comment by Dazpoet** [comment]
These files died a long time ago and I am not sure how to bring them back. Afaik our old Jenkins used to auto build them so I guess @hakan42 or @techman83 might be our best bets for a solution.

**Comment by techman83** [comment]
@hakan42 setup the jobs, which have a remote trigger. It hasn't been triggered for nearly 9 months.

**Comment by RJPercival** [comment]
Any idea how we get them triggering again?

**Comment by politas** [comment]
Talk to the Scansat team, maybe?

**Comment by RJPercival** [comment]
They consider it a CKAN issue, and not their responsibility.

**Comment by politas** [comment]
Sounds like it's never going to happen, then.

**Comment by hakan42** [comment]
Many moons ago, I had a few Jenkins jobs which took care of the *-pre jobs (see comment of @techman83 ). Unfortunately, I got sidetracked into many other things in the meantime, so I have no real clue what the current state of the build jobs is.

I cannot promise anything when I could get back to having a look at this issue again. If it happens, it will most definetly not be in April.

**Comment by hakan42** [comment]
Also, the remote trigger came from the Jenkins server operated by @sarbian ( https://ksp.sarbian.com/jenkins/ )

**Comment by sarbian** [comment]
The build there have been failing for a very long time. I can fix the build script if you want. technogeeky should have a user on my Jenkins and can fix them too (with my help if needed)

**Comment by RJPercival** [comment]
I've taken a look at the build failure and created https://github.com/S-C-A-N/SCANsat/pull/210 to fix it (but I haven't tested if there are other things that will break it afterwards).

**Comment by RJPercival** [comment]
Builds are now failing because SCANsatkethane has been removed from SCANsat (https://github.com/S-C-A-N/SCANsat/commit/991ebbca6ff51a45291ad26f4f6575899cff1c78), but the Jenkins jobs are still attempting to build it.

**Comment by sarbian** [comment]
I removed the SCANsatkethane reference in the build job and they now work. Ping me if you need other changes

**Comment by HebaruSan** [comment]
They're not coming back, see KSP-CKAN/CKAN-meta#1877.
