### ISSUE TITLE
RemoteTech-pre has not been updated since v1.6.3

### ISSUE THREAD

**Issue by RJPercival** [KSP-CKAN/CKAN-meta-dev#9]
Latest version is v1.6.9: https://github.com/RemoteTechnologiesGroup/RemoteTech/releases.

**Comment by doktorjet** [comment]
Bump.
Pre-release versions are here:  https://github.com/RemoteTechnologiesGroup/RemoteTech/releases

**Comment by politas** [comment]
I'm not sure how this repo was ever handled.

**Comment by techman83** [comment]
@politas it probably should go away. It's never been used.

**Comment by HebaruSan** [comment]
It's dead, Jim.
